# Builds site and pushes a commit into the github pages repository.

name: Deploy to pages repository

# Triggers the workflow on push events for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Builds the site
    - name: Build site
      run: |
        npm install
        npm run build
        
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.0
      with:
        target_branch: master
        build_dir: build
        repo: svargaslondono/svargaslondono.github.io
        keep_history: true
        jekyll: false
      env: 
        GH_PAT: ${{ secrets.GH_PAT }}
